export interface PersonnelItem {
  id: number;
  name: string;
  employeeNo: string;
  department: string;
  role: string;
  phone: string;
  similarityThreshold: number;
  status: '启用' | '停用';
  faceCount: number;
  lastVerifyTime: string;
  remark: string;
}

export interface StrategyItem {
  id: number;
  name: string;
  mode: '仅眨眼' | '多维度';
  sensitivity: '低' | '中' | '高';
  dimensions: string[];
  frameRule: string;
  antiReplay: '开启' | '关闭';
  status: '启用' | '停用';
  scene: string;
  updatedAt: string;
}

export interface VerificationRecordItem {
  id: number;
  name: string;
  employeeNo: string;
  department: string;
  strategyName: string;
  result: '通过' | '失败';
  score: number;
  attackType: string;
  device: string;
  verifyTime: string;
}

export interface AlarmEventItem {
  id: number;
  eventNo: string;
  area: string;
  level: '一级' | '二级' | '三级';
  source: string;
  status: '待处理' | '处理中' | '已关闭';
  handler: string;
  triggerTime: string;
  description: string;
}

export const seedPersonnelList: PersonnelItem[] = [
  {
    id: 1,
    name: '张建国',
    employeeNo: 'EMP-2026001',
    department: '生产一部',
    role: '车间主管',
    phone: '13800000001',
    similarityThreshold: 92,
    status: '启用',
    faceCount: 3,
    lastVerifyTime: '2026-04-02 09:12:33',
    remark: '白班负责人',
  },
  {
    id: 2,
    name: '李晓敏',
    employeeNo: 'EMP-2026002',
    department: '安保中心',
    role: '巡检员',
    phone: '13800000002',
    similarityThreshold: 90,
    status: '启用',
    faceCount: 2,
    lastVerifyTime: '2026-04-02 08:45:11',
    remark: '重点巡检区域 A',
  },
  {
    id: 3,
    name: '王志强',
    employeeNo: 'EMP-2026003',
    department: '设备运维部',
    role: '设备工程师',
    phone: '13800000003',
    similarityThreshold: 91,
    status: '启用',
    faceCount: 4,
    lastVerifyTime: '2026-04-01 18:06:29',
    remark: '夜班轮值',
  },
  {
    id: 4,
    name: '陈丽娜',
    employeeNo: 'EMP-2026004',
    department: '行政部',
    role: '行政专员',
    phone: '13800000004',
    similarityThreshold: 88,
    status: '停用',
    faceCount: 1,
    lastVerifyTime: '2026-03-29 14:13:47',
    remark: '离岗待停用',
  },
  {
    id: 5,
    name: '赵文博',
    employeeNo: 'EMP-2026005',
    department: '安保中心',
    role: '中控值班员',
    phone: '13800000005',
    similarityThreshold: 93,
    status: '启用',
    faceCount: 3,
    lastVerifyTime: '2026-04-02 09:03:42',
    remark: '主控室',
  },
  {
    id: 6,
    name: '刘海峰',
    employeeNo: 'EMP-2026006',
    department: '生产二部',
    role: '班组长',
    phone: '13800000006',
    similarityThreshold: 89,
    status: '启用',
    faceCount: 2,
    lastVerifyTime: '2026-04-02 07:56:23',
    remark: '晨会签到频繁',
  },
  {
    id: 7,
    name: '孙雅婷',
    employeeNo: 'EMP-2026007',
    department: '质检部',
    role: '质检员',
    phone: '13800000007',
    similarityThreshold: 90,
    status: '启用',
    faceCount: 3,
    lastVerifyTime: '2026-04-01 17:28:15',
    remark: '人脸样本完整',
  },
  {
    id: 8,
    name: '郭明轩',
    employeeNo: 'EMP-2026008',
    department: '设备运维部',
    role: '电气工程师',
    phone: '13800000008',
    similarityThreshold: 94,
    status: '启用',
    faceCount: 2,
    lastVerifyTime: '2026-04-02 08:28:54',
    remark: '高权限通道',
  },
  {
    id: 9,
    name: '黄思雨',
    employeeNo: 'EMP-2026009',
    department: '财务部',
    role: '出纳',
    phone: '13800000009',
    similarityThreshold: 87,
    status: '启用',
    faceCount: 1,
    lastVerifyTime: '2026-04-01 16:52:39',
    remark: '办公区门禁',
  },
  {
    id: 10,
    name: '周凯旋',
    employeeNo: 'EMP-2026010',
    department: '安保中心',
    role: '门岗值守',
    phone: '13800000010',
    similarityThreshold: 92,
    status: '启用',
    faceCount: 3,
    lastVerifyTime: '2026-04-02 09:18:10',
    remark: '入口 1 号门岗',
  },
  {
    id: 11,
    name: '何雨晨',
    employeeNo: 'EMP-2026011',
    department: '仓储部',
    role: '仓管员',
    phone: '13800000011',
    similarityThreshold: 90,
    status: '启用',
    faceCount: 2,
    lastVerifyTime: '2026-04-01 19:06:41',
    remark: '夜间出入较多',
  },
  {
    id: 12,
    name: '郑博文',
    employeeNo: 'EMP-2026012',
    department: '信息部',
    role: '系统管理员',
    phone: '13800000012',
    similarityThreshold: 95,
    status: '启用',
    faceCount: 5,
    lastVerifyTime: '2026-04-02 09:20:21',
    remark: '演示账号持有人',
  },
];

export const seedStrategyList: StrategyItem[] = [
  {
    id: 1,
    name: '厂区入口标准策略',
    mode: '多维度',
    sensitivity: '中',
    dimensions: ['眨眼', '摇头', '嘴部开合', '光流防翻拍'],
    frameRule: '任意 3 维度 + 连续 8 帧',
    antiReplay: '开启',
    status: '启用',
    scene: '厂区主入口',
    updatedAt: '2026-04-01 16:20:00',
  },
  {
    id: 2,
    name: '办公区快速通行策略',
    mode: '仅眨眼',
    sensitivity: '低',
    dimensions: ['眨眼'],
    frameRule: '连续 8 帧眨眼',
    antiReplay: '关闭',
    status: '启用',
    scene: '办公区内门',
    updatedAt: '2026-03-30 11:10:00',
  },
  {
    id: 3,
    name: '中控室高安全策略',
    mode: '多维度',
    sensitivity: '高',
    dimensions: ['眨眼', '摇头', '嘴部开合', '点头', '关键点运动', '光流防翻拍'],
    frameRule: '任意 4 维度 + 连续 10 帧',
    antiReplay: '开启',
    status: '启用',
    scene: '中控室',
    updatedAt: '2026-04-02 08:00:00',
  },
  {
    id: 4,
    name: '夜间巡检策略',
    mode: '多维度',
    sensitivity: '中',
    dimensions: ['眨眼', '摇头', '关键点运动'],
    frameRule: '任意 2 维度 + 连续 8 帧',
    antiReplay: '开启',
    status: '停用',
    scene: '夜巡路线',
    updatedAt: '2026-03-28 21:32:00',
  },
  {
    id: 5,
    name: '访客临时校验策略',
    mode: '多维度',
    sensitivity: '中',
    dimensions: ['眨眼', '嘴部开合', '光流防翻拍'],
    frameRule: '任意 2 维度 + 连续 6 帧',
    antiReplay: '开启',
    status: '启用',
    scene: '访客机',
    updatedAt: '2026-04-01 09:40:00',
  },
  {
    id: 6,
    name: '测试环境回归策略',
    mode: '仅眨眼',
    sensitivity: '高',
    dimensions: ['眨眼'],
    frameRule: '连续 8 帧眨眼',
    antiReplay: '关闭',
    status: '停用',
    scene: '测试环境',
    updatedAt: '2026-03-26 14:00:00',
  },
];

export const seedVerificationRecordList: VerificationRecordItem[] = [
  {
    id: 1,
    name: '张建国',
    employeeNo: 'EMP-2026001',
    department: '生产一部',
    strategyName: '厂区入口标准策略',
    result: '通过',
    score: 98,
    attackType: '真人',
    device: 'Gate-Cam-01',
    verifyTime: '2026-04-02 09:12:33',
  },
  {
    id: 2,
    name: '李晓敏',
    employeeNo: 'EMP-2026002',
    department: '安保中心',
    strategyName: '中控室高安全策略',
    result: '通过',
    score: 97,
    attackType: '真人',
    device: 'Ctrl-Cam-02',
    verifyTime: '2026-04-02 08:45:11',
  },
  {
    id: 3,
    name: '匿名访客',
    employeeNo: 'VIS-0001',
    department: '访客',
    strategyName: '访客临时校验策略',
    result: '失败',
    score: 61,
    attackType: '电子屏翻拍',
    device: 'Guest-Cam-01',
    verifyTime: '2026-04-02 08:31:20',
  },
  {
    id: 4,
    name: '王志强',
    employeeNo: 'EMP-2026003',
    department: '设备运维部',
    strategyName: '厂区入口标准策略',
    result: '通过',
    score: 95,
    attackType: '真人',
    device: 'Gate-Cam-03',
    verifyTime: '2026-04-01 18:06:29',
  },
  {
    id: 5,
    name: '赵文博',
    employeeNo: 'EMP-2026005',
    department: '安保中心',
    strategyName: '中控室高安全策略',
    result: '通过',
    score: 99,
    attackType: '真人',
    device: 'Ctrl-Cam-01',
    verifyTime: '2026-04-02 09:03:42',
  },
  {
    id: 6,
    name: '模拟攻击样本 A',
    employeeNo: 'SIM-1001',
    department: '测试组',
    strategyName: '测试环境回归策略',
    result: '失败',
    score: 52,
    attackType: '短视频攻击',
    device: 'Test-Cam-01',
    verifyTime: '2026-04-01 15:42:08',
  },
  {
    id: 7,
    name: '刘海峰',
    employeeNo: 'EMP-2026006',
    department: '生产二部',
    strategyName: '厂区入口标准策略',
    result: '通过',
    score: 94,
    attackType: '真人',
    device: 'Gate-Cam-02',
    verifyTime: '2026-04-02 07:56:23',
  },
  {
    id: 8,
    name: '郭明轩',
    employeeNo: 'EMP-2026008',
    department: '设备运维部',
    strategyName: '中控室高安全策略',
    result: '通过',
    score: 99,
    attackType: '真人',
    device: 'Ctrl-Cam-02',
    verifyTime: '2026-04-02 08:28:54',
  },
  {
    id: 9,
    name: '周凯旋',
    employeeNo: 'EMP-2026010',
    department: '安保中心',
    strategyName: '厂区入口标准策略',
    result: '通过',
    score: 96,
    attackType: '真人',
    device: 'Gate-Cam-01',
    verifyTime: '2026-04-02 09:18:10',
  },
  {
    id: 10,
    name: '临时访客 B',
    employeeNo: 'VIS-0002',
    department: '访客',
    strategyName: '访客临时校验策略',
    result: '失败',
    score: 58,
    attackType: '静态照片',
    device: 'Guest-Cam-01',
    verifyTime: '2026-04-02 09:05:44',
  },
  {
    id: 11,
    name: '何雨晨',
    employeeNo: 'EMP-2026011',
    department: '仓储部',
    strategyName: '办公区快速通行策略',
    result: '通过',
    score: 90,
    attackType: '真人',
    device: 'Office-Cam-02',
    verifyTime: '2026-04-01 19:06:41',
  },
  {
    id: 12,
    name: '郑博文',
    employeeNo: 'EMP-2026012',
    department: '信息部',
    strategyName: '中控室高安全策略',
    result: '通过',
    score: 100,
    attackType: '真人',
    device: 'Ctrl-Cam-01',
    verifyTime: '2026-04-02 09:20:21',
  },
  {
    id: 13,
    name: '孙雅婷',
    employeeNo: 'EMP-2026007',
    department: '质检部',
    strategyName: '办公区快速通行策略',
    result: '通过',
    score: 91,
    attackType: '真人',
    device: 'Office-Cam-01',
    verifyTime: '2026-04-01 17:28:15',
  },
  {
    id: 14,
    name: '黄思雨',
    employeeNo: 'EMP-2026009',
    department: '财务部',
    strategyName: '办公区快速通行策略',
    result: '通过',
    score: 89,
    attackType: '真人',
    device: 'Office-Cam-03',
    verifyTime: '2026-04-01 16:52:39',
  },
  {
    id: 15,
    name: '模拟攻击样本 B',
    employeeNo: 'SIM-1002',
    department: '测试组',
    strategyName: '厂区入口标准策略',
    result: '失败',
    score: 49,
    attackType: '电子屏翻拍',
    device: 'Gate-Cam-03',
    verifyTime: '2026-04-01 13:22:58',
  },
];

export const seedAlarmEventList: AlarmEventItem[] = [
  {
    id: 1,
    eventNo: 'ALM-20260402-001',
    area: '厂区东门',
    level: '二级',
    source: '防撞传感器',
    status: '已关闭',
    handler: '赵文博',
    triggerTime: '2026-04-02 08:10:22',
    description: '叉车接近阈值触发预警，已人工确认解除。',
  },
  {
    id: 2,
    eventNo: 'ALM-20260402-002',
    area: '访客通道',
    level: '一级',
    source: '活体检测拦截',
    status: '处理中',
    handler: '李晓敏',
    triggerTime: '2026-04-02 08:31:20',
    description: '电子屏翻拍攻击触发高等级预警。',
  },
  {
    id: 3,
    eventNo: 'ALM-20260402-003',
    area: '中控室外侧',
    level: '三级',
    source: '门禁异常联动',
    status: '待处理',
    handler: '未分配',
    triggerTime: '2026-04-02 08:46:55',
    description: '识别失败后重复尝试次数异常。',
  },
  {
    id: 4,
    eventNo: 'ALM-20260401-011',
    area: '厂区主入口',
    level: '二级',
    source: '防撞传感器',
    status: '已关闭',
    handler: '周凯旋',
    triggerTime: '2026-04-01 17:12:11',
    description: '人员聚集靠近车辆通道，现场广播提示后解除。',
  },
  {
    id: 5,
    eventNo: 'ALM-20260401-012',
    area: '办公区南门',
    level: '三级',
    source: '活体检测拦截',
    status: '已关闭',
    handler: '孙雅婷',
    triggerTime: '2026-04-01 16:08:44',
    description: '静态照片攻击被系统拦截。',
  },
  {
    id: 6,
    eventNo: 'ALM-20260401-013',
    area: '仓储通道',
    level: '二级',
    source: '防撞传感器',
    status: '处理中',
    handler: '刘海峰',
    triggerTime: '2026-04-01 19:02:08',
    description: '夜间巡检期间小车距离过近。',
  },
  {
    id: 7,
    eventNo: 'ALM-20260331-021',
    area: '测试环境',
    level: '一级',
    source: '演练数据注入',
    status: '已关闭',
    handler: '郑博文',
    triggerTime: '2026-03-31 14:40:00',
    description: '演示环境模拟短视频攻击成功触发预警。',
  },
  {
    id: 8,
    eventNo: 'ALM-20260331-022',
    area: '中控室',
    level: '一级',
    source: '门禁异常联动',
    status: '已关闭',
    handler: '赵文博',
    triggerTime: '2026-03-31 18:20:15',
    description: '高权限区域重复识别失败，已核验无风险。',
  },
];
