/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElLoading: typeof import('element-plus')['ElLoading']
  const ElMessage: typeof import('element-plus')['ElMessage']
  const ElMessageBox: typeof import('element-plus')['ElMessageBox']
  const useAuth: typeof import('../composables/use-auth')['useAuth']
  const useEcharts: typeof import('../composables/use-echarts')['useEcharts']
  const useI18n: typeof import('../composables/use-i18n')['useI18n']
  const useLoadView: typeof import('../composables/use-load-view')['useLoadView']
  const useNotificationState: typeof import('@/components/systems/notifications/use-notification-state')['useNotificationState']
  const usePreferences: typeof import('../composables/use-preferences')['usePreferences']
  const usePreferencesStore: typeof import('@/store/modules/preferences')['usePreferencesStore']
  const useSettingState: typeof import('@/components/systems/settings/use-setting-state')['useSettingState']
  const useTheme: typeof import('../composables/use-theme')['useTheme']
  const useUserStore: typeof import('@/store/modules/user')['useUserStore']
}
